/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutboundRouteImport } from './routes/outbound'
import { Route as CallHistoryRouteImport } from './routes/call-history'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallHistoryConversationIdRouteImport } from './routes/call-history.$conversationId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as ApiAudioConversationIdRouteImport } from './routes/api/audio.$conversationId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundRoute = OutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHistoryRoute = CallHistoryRouteImport.update({
  id: '/call-history',
  path: '/call-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHistoryConversationIdRoute =
  CallHistoryConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => CallHistoryRoute,
  } as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)
const ApiAudioConversationIdRoute = ApiAudioConversationIdRouteImport.update({
  id: '/api/audio/$conversationId',
  path: '/api/audio/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/call-history': typeof CallHistoryRouteWithChildren
  '/outbound': typeof OutboundRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/call-history/$conversationId': typeof CallHistoryConversationIdRoute
  '/api/audio/$conversationId': typeof ApiAudioConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/call-history': typeof CallHistoryRouteWithChildren
  '/outbound': typeof OutboundRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/call-history/$conversationId': typeof CallHistoryConversationIdRoute
  '/api/audio/$conversationId': typeof ApiAudioConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/call-history': typeof CallHistoryRouteWithChildren
  '/outbound': typeof OutboundRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/call-history/$conversationId': typeof CallHistoryConversationIdRoute
  '/api/audio/$conversationId': typeof ApiAudioConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/call-history'
    | '/outbound'
    | '/settings'
    | '/support'
    | '/agents/$agentId'
    | '/call-history/$conversationId'
    | '/api/audio/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/call-history'
    | '/outbound'
    | '/settings'
    | '/support'
    | '/agents/$agentId'
    | '/call-history/$conversationId'
    | '/api/audio/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/call-history'
    | '/outbound'
    | '/settings'
    | '/support'
    | '/agents/$agentId'
    | '/call-history/$conversationId'
    | '/api/audio/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  CallHistoryRoute: typeof CallHistoryRouteWithChildren
  OutboundRoute: typeof OutboundRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  ApiAudioConversationIdRoute: typeof ApiAudioConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound': {
      id: '/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof OutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-history': {
      id: '/call-history'
      path: '/call-history'
      fullPath: '/call-history'
      preLoaderRoute: typeof CallHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-history/$conversationId': {
      id: '/call-history/$conversationId'
      path: '/$conversationId'
      fullPath: '/call-history/$conversationId'
      preLoaderRoute: typeof CallHistoryConversationIdRouteImport
      parentRoute: typeof CallHistoryRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/api/audio/$conversationId': {
      id: '/api/audio/$conversationId'
      path: '/api/audio/$conversationId'
      fullPath: '/api/audio/$conversationId'
      preLoaderRoute: typeof ApiAudioConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface CallHistoryRouteChildren {
  CallHistoryConversationIdRoute: typeof CallHistoryConversationIdRoute
}

const CallHistoryRouteChildren: CallHistoryRouteChildren = {
  CallHistoryConversationIdRoute: CallHistoryConversationIdRoute,
}

const CallHistoryRouteWithChildren = CallHistoryRoute._addFileChildren(
  CallHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  CallHistoryRoute: CallHistoryRouteWithChildren,
  OutboundRoute: OutboundRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  ApiAudioConversationIdRoute: ApiAudioConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
